# Generated by Django 5.0.4 on 2024-05-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file_classification'),
    ]

    operations = [
    ]
