# Generated by Django 5.0.4 on 2024-05-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
