# Generated by Django 5.0.4 on 2024-05-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
