# Generated by Django 5.0.4 on 2024-05-15 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
