# Generated by Django 5.0.4 on 2024-05-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
